####################################################################################
## Copyright (c) 2018 - 2023 Analog Devices, Inc.
### SPDX short identifier: BSD-1-Clause
####################################################################################

PROJECT_NAME := imageon_ebaz4205

M_DEPS += ../../scripts/adi_pd.tcl
M_DEPS += ../../common/ebaz4205/ebaz4205_system_bd.tcl

LIB_DEPS += axi_i2s_adi
LIB_DEPS += axi_spdif_tx
LIB_DEPS += axi_sysid
LIB_DEPS += sysid_rom
LIB_DEPS += eece4534/axi_muxer

include ../../scripts/project-xilinx.mk
