// ***************************************************************************
// EBAZ4205 + expansion board system top-level
// ***************************************************************************

`timescale 1ns/100ps

module system_top (

  // DDR
  inout   [14:0]  ddr_addr,
  inout   [ 2:0]  ddr_ba,
  inout           ddr_cas_n,
  inout           ddr_ck_n,
  inout           ddr_ck_p,
  inout           ddr_cke,
  inout           ddr_cs_n,
  inout   [ 1:0]  ddr_dm,
  inout   [15:0]  ddr_dq,
  inout   [ 1:0]  ddr_dqs_n,
  inout   [ 1:0]  ddr_dqs_p,
  inout           ddr_odt,
  inout           ddr_ras_n,
  inout           ddr_reset_n,
  inout           ddr_we_n,

  // PS fixed IO
  inout           fixed_io_ddr_vrn,
  inout           fixed_io_ddr_vrp,
  inout   [53:0]  fixed_io_mio,
  inout           fixed_io_ps_clk,
  inout           fixed_io_ps_porb,
  inout           fixed_io_ps_srstb,

  // ENET0 EMIO MII
  input   [ 3:0]  ENET0_GMII_RXD_0,
  input           ENET0_GMII_RX_CLK_0,
  input           ENET0_GMII_RX_DV_0,
  input           ENET0_GMII_TX_CLK_0,
  output  [ 3:0]  ENET0_GMII_TXD_0,
  output  [ 0:0]  ENET0_GMII_TX_EN_0,
  output          MDIO_ETHERNET_0_0_mdc,
  inout           MDIO_ETHERNET_0_0_mdio_io,

  // On-board LEDs: [0]=green(W13), [1]=red(W14)
  output  [ 1:0]  board_led,

  // Extension LEDs: [0..2]=E19/K17/H18, [3..7]=G20/J18/G19/H20/J19
  output  [ 7:0]  ext_led,

  // DIP Switches: 8x (K18..M20)
  input   [ 7:0]  sw,

  // Push Buttons: 5x expansion
  input   [ 4:0]  board_btn,

  // LCD ST7789 SPI + control
  output          lcd_scl,
  output          lcd_sda,
  output  [ 2:0]  lcd_ctl,    // [0]=DC, [1]=RST, [2]=BL

  // CH340 UART
  input           uart_rxd,
  output          uart_txd,

  // PWM: [0]=J5_PWM(V12), [1]=J3_PWM(U12)
  output  [ 1:0]  pwm_out,

  // Timer tachometer inputs
  input           tmr_capture,    // J5_SPEED V15
  input           tmr_capture2,   // J3_SPEED V13

  // I2S audio (PCM5102A, 3-wire mode — MCLK generated by BD clkgen)
  output          i2s_bclk,
  output          i2s_lrclk,
  output          i2s_sdata_out,

  // SPDIF output (no physical pin on EBAZ — can leave unconnected)

  // I2C main (axi_iic_main)
  inout           iic_main_scl_io,
  inout           iic_main_sda_io,

);

  // -------------------------------------------------------------------------
  // Internal wires
  // -------------------------------------------------------------------------

  // lcd_ctl: BD drives [4:0], only [2:0] have physical pins; [4:3] float
  wire  [ 2:0]  lcd_ctl_bd;
  assign lcd_ctl = lcd_ctl_bd;

  // I2S interface bus
  // I2S signals connected directly to wrapper ports

  // I2C main — IOBUF generated automatically by system_wrapper (IIC interface bundle)


  // -------------------------------------------------------------------------
  // System wrapper instantiation
  // -------------------------------------------------------------------------
  system_wrapper i_system_wrapper (

    .ddr_addr                   (ddr_addr),
    .ddr_ba                     (ddr_ba),
    .ddr_cas_n                  (ddr_cas_n),
    .ddr_ck_n                   (ddr_ck_n),
    .ddr_ck_p                   (ddr_ck_p),
    .ddr_cke                    (ddr_cke),
    .ddr_cs_n                   (ddr_cs_n),
    .ddr_dm                     (ddr_dm),
    .ddr_dq                     (ddr_dq),
    .ddr_dqs_n                  (ddr_dqs_n),
    .ddr_dqs_p                  (ddr_dqs_p),
    .ddr_odt                    (ddr_odt),
    .ddr_ras_n                  (ddr_ras_n),
    .ddr_reset_n                (ddr_reset_n),
    .ddr_we_n                   (ddr_we_n),

    .fixed_io_ddr_vrn           (fixed_io_ddr_vrn),
    .fixed_io_ddr_vrp           (fixed_io_ddr_vrp),
    .fixed_io_mio               (fixed_io_mio),
    .fixed_io_ps_clk            (fixed_io_ps_clk),
    .fixed_io_ps_porb           (fixed_io_ps_porb),
    .fixed_io_ps_srstb          (fixed_io_ps_srstb),

    .ENET0_GMII_RXD_0           (ENET0_GMII_RXD_0),
    .ENET0_GMII_RX_CLK_0        (ENET0_GMII_RX_CLK_0),
    .ENET0_GMII_RX_DV_0         (ENET0_GMII_RX_DV_0),
    .ENET0_GMII_TX_CLK_0        (ENET0_GMII_TX_CLK_0),
    .ENET0_GMII_TXD_0           (ENET0_GMII_TXD_0),
    .ENET0_GMII_TX_EN_0         (ENET0_GMII_TX_EN_0),
    .MDIO_ETHERNET_0_0_mdc      (MDIO_ETHERNET_0_0_mdc),
    .MDIO_ETHERNET_0_0_mdio_io  (MDIO_ETHERNET_0_0_mdio_io),

    .board_led                  (board_led),
    .ext_led                    (ext_led),
    .sw                         (sw),
    .board_btn                  (board_btn),

    .lcd_scl                    (lcd_scl),
    .lcd_sda                    (lcd_sda),
    .lcd_ctl                    (lcd_ctl_bd[2:0]),

    .uart_rxd                   (uart_rxd),
    .uart_txd                   (uart_txd),

    .pwm_out                    (pwm_out),
    .tmr_capture                (tmr_capture),
    .tmr_capture2               (tmr_capture2),

    .i2s_bclk                   (i2s_bclk),
    .i2s_lrclk                  (i2s_lrclk),
    .i2s_sdata_out              (i2s_sdata_out),



    .iic_main_scl_io            (iic_main_scl_io),
    .iic_main_sda_io            (iic_main_sda_io),


  );

endmodule
