// ***************************************************************************
// EBAZ4205 + expansion board system top-level
// ***************************************************************************

`timescale 1ns/100ps

module system_top (

  // DDR
  inout   [14:0]  ddr_addr,
  inout   [ 2:0]  ddr_ba,
  inout           ddr_cas_n,
  inout           ddr_ck_n,
  inout           ddr_ck_p,
  inout           ddr_cke,
  inout           ddr_cs_n,
  inout   [ 1:0]  ddr_dm,
  inout   [15:0]  ddr_dq,
  inout   [ 1:0]  ddr_dqs_n,
  inout   [ 1:0]  ddr_dqs_p,
  inout           ddr_odt,
  inout           ddr_ras_n,
  inout           ddr_reset_n,
  inout           ddr_we_n,

  // PS fixed IO
  inout           fixed_io_ddr_vrn,
  inout           fixed_io_ddr_vrp,
  inout   [53:0]  fixed_io_mio,
  inout           fixed_io_ps_clk,
  inout           fixed_io_ps_porb,
  inout           fixed_io_ps_srstb,

  // ENET0 EMIO MII
  input   [ 3:0]  ENET0_GMII_RXD_0,
  input           ENET0_GMII_RX_CLK_0,
  input           ENET0_GMII_RX_DV_0,
  input           ENET0_GMII_TX_CLK_0,
  output  [ 3:0]  ENET0_GMII_TXD_0,
  output  [ 0:0]  ENET0_GMII_TX_EN_0,
  output          MDIO_ETHERNET_0_0_mdc,
  inout           MDIO_ETHERNET_0_0_mdio_io,

  // On-board LEDs: [0]=green(W13), [1]=red(W14)
  output  [ 1:0]  board_led,

  // Extension LEDs: [0..2]=E19/K17/H18, [3..7]=G20/J18/G19/H20/J19
  output  [ 7:0]  ext_led,

  // DIP Switches: 8x (K18..M20)
  input   [ 7:0]  sw,

  // Push Buttons: 5x expansion
  input   [ 4:0]  board_btn,

  // LCD ST7789 SPI + control
  output          lcd_scl,
  output          lcd_sda,
  output  [ 4:0]  lcd_ctl,    // [0]=DC, [1]=RST, [2]=BL, [4:3]=spare/unused

  // CH340 UART
  input           uart_rxd,
  output          uart_txd,

  // PWM: [0]=J5_PWM(V12), [1]=J3_PWM(U12)
  output  [ 1:0]  pwm_out,

  // Timer tachometer inputs
  input           tmr_capture,    // J5_SPEED V15
  input           tmr_capture2,   // J3_SPEED V13

  // I2S audio (PCM5102A, 3-wire mode — MCLK generated by BD clkgen)
  output          i2s_mclk,
  output          i2s_bclk,
  output          i2s_lrclk,
  output          i2s_sdata_out,

  // SPDIF output (no physical pin on EBAZ — can leave unconnected)
  output          spdif,

  // I2C main (axi_iic_main)
  inout           iic_main_scl,
  inout           iic_main_sda,

  // I2C spare (axi_iic_ext)
  inout           iic_ext_scl,
  inout           iic_ext_sda

);

  // -------------------------------------------------------------------------
  // Internal wires
  // -------------------------------------------------------------------------
  wire  [63:0]  gpio_i;
  wire  [63:0]  gpio_o;
  wire  [63:0]  gpio_t;
  assign gpio_i = 64'h0;

  // lcd_ctl: BD drives [4:0], only [2:0] have physical pins; [4:3] float
  wire  [ 4:0]  lcd_ctl_bd;
  assign lcd_ctl = lcd_ctl_bd;

  // I2S interface bus
  wire          i2s_bclk_s;
  wire          i2s_lrclk_s;
  wire          i2s_sdata_out_s;
  wire          i2s_sdata_in_s;
  assign i2s_bclk      = i2s_bclk_s;
  assign i2s_lrclk     = i2s_lrclk_s;
  assign i2s_sdata_out = i2s_sdata_out_s;
  assign i2s_sdata_in_s = 1'b0;  // DAC only, no ADC

  // I2C tri-state buffers — iic_main
  wire  iic_main_scl_i_s, iic_main_scl_o_s, iic_main_scl_t_s;
  wire  iic_main_sda_i_s, iic_main_sda_o_s, iic_main_sda_t_s;

  ad_iobuf #(.DATA_WIDTH(1)) i_iic_main_scl (
    .dio_t (iic_main_scl_t_s),
    .dio_i (iic_main_scl_o_s),
    .dio_o (iic_main_scl_i_s),
    .dio_p (iic_main_scl)
  );
  ad_iobuf #(.DATA_WIDTH(1)) i_iic_main_sda (
    .dio_t (iic_main_sda_t_s),
    .dio_i (iic_main_sda_o_s),
    .dio_o (iic_main_sda_i_s),
    .dio_p (iic_main_sda)
  );

  // I2C tri-state buffers — iic_ext
  wire  iic_ext_scl_i_s, iic_ext_scl_o_s, iic_ext_scl_t_s;
  wire  iic_ext_sda_i_s, iic_ext_sda_o_s, iic_ext_sda_t_s;

  ad_iobuf #(.DATA_WIDTH(1)) i_iic_ext_scl (
    .dio_t (iic_ext_scl_t_s),
    .dio_i (iic_ext_scl_o_s),
    .dio_o (iic_ext_scl_i_s),
    .dio_p (iic_ext_scl)
  );
  ad_iobuf #(.DATA_WIDTH(1)) i_iic_ext_sda (
    .dio_t (iic_ext_sda_t_s),
    .dio_i (iic_ext_sda_o_s),
    .dio_o (iic_ext_sda_i_s),
    .dio_p (iic_ext_sda)
  );

  // -------------------------------------------------------------------------
  // System wrapper instantiation
  // -------------------------------------------------------------------------
  system_wrapper i_system_wrapper (

    .ddr_addr                   (ddr_addr),
    .ddr_ba                     (ddr_ba),
    .ddr_cas_n                  (ddr_cas_n),
    .ddr_ck_n                   (ddr_ck_n),
    .ddr_ck_p                   (ddr_ck_p),
    .ddr_cke                    (ddr_cke),
    .ddr_cs_n                   (ddr_cs_n),
    .ddr_dm                     (ddr_dm),
    .ddr_dq                     (ddr_dq),
    .ddr_dqs_n                  (ddr_dqs_n),
    .ddr_dqs_p                  (ddr_dqs_p),
    .ddr_odt                    (ddr_odt),
    .ddr_ras_n                  (ddr_ras_n),
    .ddr_reset_n                (ddr_reset_n),
    .ddr_we_n                   (ddr_we_n),

    .fixed_io_ddr_vrn           (fixed_io_ddr_vrn),
    .fixed_io_ddr_vrp           (fixed_io_ddr_vrp),
    .fixed_io_mio               (fixed_io_mio),
    .fixed_io_ps_clk            (fixed_io_ps_clk),
    .fixed_io_ps_porb           (fixed_io_ps_porb),
    .fixed_io_ps_srstb          (fixed_io_ps_srstb),

    .ENET0_GMII_RXD_0           (ENET0_GMII_RXD_0),
    .ENET0_GMII_RX_CLK_0        (ENET0_GMII_RX_CLK_0),
    .ENET0_GMII_RX_DV_0         (ENET0_GMII_RX_DV_0),
    .ENET0_GMII_TX_CLK_0        (ENET0_GMII_TX_CLK_0),
    .ENET0_GMII_TXD_0           (ENET0_GMII_TXD_0),
    .ENET0_GMII_TX_EN_0         (ENET0_GMII_TX_EN_0),
    .MDIO_ETHERNET_0_0_mdc      (MDIO_ETHERNET_0_0_mdc),
    .MDIO_ETHERNET_0_0_mdio_io  (MDIO_ETHERNET_0_0_mdio_io),

    .board_led                  (board_led),
    .ext_led                    (ext_led),
    .sw                         (sw),
    .board_btn                  (board_btn),

    .lcd_scl                    (lcd_scl),
    .lcd_sda                    (lcd_sda),
    .lcd_ctl                    (lcd_ctl_bd),

    .uart_rxd                   (uart_rxd),
    .uart_txd                   (uart_txd),

    .pwm_out                    (pwm_out),
    .tmr_capture                (tmr_capture),
    .tmr_capture2               (tmr_capture2),

    .i2s_mclk                   (i2s_mclk),
    .i2s                        ({i2s_bclk_s, i2s_lrclk_s, i2s_sdata_out_s, i2s_sdata_in_s}),

    .spdif                      (spdif),

    .iic_main_scl_i             (iic_main_scl_i_s),
    .iic_main_scl_o             (iic_main_scl_o_s),
    .iic_main_scl_t             (iic_main_scl_t_s),
    .iic_main_sda_i             (iic_main_sda_i_s),
    .iic_main_sda_o             (iic_main_sda_o_s),
    .iic_main_sda_t             (iic_main_sda_t_s),

    .iic_ext_scl_i              (iic_ext_scl_i_s),
    .iic_ext_scl_o              (iic_ext_scl_o_s),
    .iic_ext_scl_t              (iic_ext_scl_t_s),
    .iic_ext_sda_i              (iic_ext_sda_i_s),
    .iic_ext_sda_o              (iic_ext_sda_o_s),
    .iic_ext_sda_t              (iic_ext_sda_t_s),

    .gpio_i                     (gpio_i),
    .gpio_o                     (gpio_o),
    .gpio_t                     (gpio_t)
  );

endmodule
